### ISSUE TITLE
Stack overflow in regexp matcher

### ISSUE THREAD

**Issue by proksi21** [thunknyc/emacs-treadmill#1]
1) Run Treadmill REPL
2) Type '(import :std/'
3) Get an error "error in process filter: Stack overflow in regexp matcher"

**Comment by edw** [comment]
This was being caused by using an inefficient method for grabbing results from a REPL process buffer. Additionally, the communication between Emacs and Gerbil was extremely chatty — it sent every match and its "etymology", when the latter is only necessary if Company asks for meta about the match.

All of this has been fixed and Emacs no longer explodes on my machine. Please update both gerbil-treadmill and emacs-treadmill and verify that you no longer get an error.
